### ISSUE TITLE
Mapping score about Human Kidney Reference

### ISSUE THREAD

**Issue by soontide** [satijalab/azimuth#109]
Dear Azimuth Dev. Team,

We have been using Azimuth as the primary choice for cell type annotation. As our server does not support GUI, we used the _Analysis script template_ for Azimuth analysis instead. Unfortunately, we rencently found there is a problem when fetching the _mapping score_ from **Human Kidney** Reference.

More exactly, when running 
_query[["proj.umap"]] <- RunUMAP( object = query[["query_ref.nn"]], reduction.model = reference$map[["refUMAP"]], reduction.key = 'UMAP_')_

it returned a warning message:
_In RunUMAP.default(object = neighborlist, reduction.model = reduction.model,  :
  Number of neighbors between query and reference is not equal to the number of neighbros within reference_

Then, for the next step
_query <- AddMetaData( object = query, metadata = MappingScore(anchors = anchors), col.name = "mapping.score")_

it further returned an error
_Error in index$getNNsByVectorList(query[x, ], k, search.k, include.distance) : 
  fv.size() != vector_size_

This problem is **NOT** observed in our previously used references like **Human PBMC, Human Fetus and Human Lung v1**. So perhaps there is a few special setting for **Human Kidney** reference that has not been specified in the corresponding _Analysis script template_?

Please tell us how to modify the script at your convenience.

Thank you!

**Comment by AustinHartman** [comment]
Instead of using the analysis script I'd recommend using `RunAzimuth` as demonstrated [here](https://satijalab.github.io/azimuth/articles/run_azimuth_tutorial.html)
