### ISSUE TITLE
Error when generating personal reference from integrated data

### ISSUE THREAD

**Issue by wmacnair** [satijalab/azimuth#112]
Hi

I would like to try out using Azimuth to map labels from my own data onto some public data. I have been trying to follow the script in `AzimuthReference` (script [here](https://github.com/satijalab/azimuth-references/blob/master/human_motorcortex/scripts/export.R)), but I run into an error at the `AzimuthReference` call:
```
seu_azi = AzimuthReference(
  object      = seu_ref,
  refUMAP     = "umap",
  refDR       = "pca",
  refAssay    = "integrated",
  metadata    = c("type_broad", "type_fine"),
  dims        = 1:30,
  k.param     = 31,
  reference.version = "1.0.0"
)
# Error in AzimuthReference(object = seu_ref, refUMAP = "umap", refDR = "pca",  :
#  refAssay (integrated) is not an SCTAssay.
```

I've looked at the [wiki](https://github.com/satijalab/azimuth/wiki/Azimuth-Reference-Format), and it says: 'Azimuth expects there to be one `SCTAssay` present in the reference object that is named "refAssay"'. Does this mean that it's not possible to map to a reference where I've integrated multiple samples? Or is there a way round this?

Thanks!
Will

**Comment by xblaezboy** [comment]
`>   tmp <- RunAzimuth(pbmc23, reference = "./pbmcref/inst/azimuth/")`


`detected inputs from HUMAN with id type Gene.name
reference rownames detected HUMAN with id type Gene.name
Using reference SCTModel to calculate pearson residuals
Determine variable features
Setting min_variance to:  -Inf
Calculating residuals of type pearson for 4999 genes
  |==========================================================================================| 100%
  |==========================================================================================| 100%
Set default assay to refAssay
Normalizing query using reference SCT model
Projecting cell embeddings
Finding query neighbors
Finding neighborhoods
Finding anchors
	Found 23802 anchors
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l1_ to predictionscorecelltypel1_
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l2_ to predictionscorecelltypel2_
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l3_ to predictionscorecelltypel3_
  |                                                  | 0 % ~calculating  
Integrating dataset 2 with reference dataset
Finding integration vectors
Integrating data
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from integrated_dr_ to integrateddr_
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03s  
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from integrated_dr_ to integrateddr_
Warning: All keys should be one or more alphanumeric characters followed by an underscore '_', setting key to integrateddr_
Computing nearest neighbors
Running UMAP projection
Error in if (num_precomputed_nns == 1 && nn_is_single(nn_method)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In RunUMAP.default(object = neighborlist, reduction.model = reduction.model,  :
  Number of neighbors between query and reference is not equal to the number of neighbros within reference`


**I don‘t know what happen，Is there some naming error in my data
I remember once I allowed to succeed. I don't know why**

**Comment by xblaezboy** [comment]
`detected inputs from HUMAN with id type Gene.name
reference rownames detected HUMAN with id type Gene.name
Using reference SCTModel to calculate pearson residuals
Determine variable features
Setting min_variance to:  -Inf
Calculating residuals of type pearson for 4999 genes
  |==========================================================================================| 100%
  |==========================================================================================| 100%
Set default assay to refAssay
Normalizing query using reference SCT model
Projecting cell embeddings
Finding query neighbors
Finding neighborhoods
Finding anchors
	Found 23802 anchors
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l1_ to predictionscorecelltypel1_
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l2_ to predictionscorecelltypel2_
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l3_ to predictionscorecelltypel3_
  |                                                  | 0 % ~calculating  
Integrating dataset 2 with reference dataset
Finding integration vectors
Integrating data
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from integrated_dr_ to integrateddr_
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03s  
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from integrated_dr_ to integrateddr_
Warning: All keys should be one or more alphanumeric characters followed by an underscore '_', setting key to integrateddr_
Computing nearest neighbors
Running UMAP projection
Error in if (num_precomputed_nns == 1 && nn_is_single(nn_method)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In RunUMAP.default(object = neighborlist, reduction.model = reduction.model,  :
  Number of neighbors between query and reference is not equal to the number of neighbros within reference`

**Comment by xblaezboy** [comment]
detected inputs from HUMAN with id type Gene.name
reference rownames detected HUMAN with id type Gene.name
Using reference SCTModel to calculate pearson residuals
Determine variable features
Setting min_variance to:  -Inf
Calculating residuals of type pearson for 4999 genes
  |==========================================================================================| 100%
  |==========================================================================================| 100%
Set default assay to refAssay
Normalizing query using reference SCT model
Projecting cell embeddings
Finding query neighbors
Finding neighborhoods
Finding anchors
	Found 23802 anchors
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l1_ to predictionscorecelltypel1_
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l2_ to predictionscorecelltypel2_
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l3_ to predictionscorecelltypel3_
  |                                                  | 0 % ~calculating  
Integrating dataset 2 with reference dataset
Finding integration vectors
Integrating data
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from integrated_dr_ to integrateddr_
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03s  
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from integrated_dr_ to integrateddr_
Warning: All keys should be one or more alphanumeric characters followed by an underscore '_', setting key to integrateddr_
Computing nearest neighbors
Running UMAP projection
Error in if (num_precomputed_nns == 1 && nn_is_single(nn_method)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In RunUMAP.default(object = neighborlist, reduction.model = reduction.model,  :
  Number of neighbors between query and reference is not equal to the number of neighbros within reference


`>   tmp <- RunAzimuth(zdsyq23, reference = "./pbmcref/inst/azimuth/")`

**I don‘t know what happen，Is there some naming error in my data
I remember once I allowed to succeed. I don't know why**

**Comment by AustinHartman** [comment]
Hi [xblaezboy](https://github.com/xblaezboy), this error is likely arising from a change in the latest version of the uwot package. Could you first confirm that you have v0.1.13 installed? If so, I'd recommend downgrading to uwot v0.1.11 with `install.packages("https://cran.r-project.org/src/contrib/Archive/uwot/uwot_0.1.11.tar.gz")` and rerunning. Hope this helps and if the issue persists feel free to open a separate issue

**Comment by AustinHartman** [comment]
Hi @wmacnair, it is possible to map to a reference derived from integrating multiple samples, but Azimuth requires the reference be normalized using SCTransform. You can try rerunning your integration with SCT as the `normalization.method` so that the integrated assay is an `SCTAssay`

**Comment by wmacnair** [comment]
Hi, just noticed I had left this open...

@AustinHartman had the right solution here - I needed to choose the right integration before calling `AzimuthReference`. 

In case it's useful to any other Seurat amateurs, my code ended up looking like this:
```
  common_gs   = SelectIntegrationFeatures(object.list = seu_ls)
  seu_anchors = FindIntegrationAnchors(object.list = seu_ls, 
    anchor.features = common_gs)
  # seu_ref     = IntegrateData(anchorset = seu_anchors) # this was the line that was wrong before
  seu_ref     = IntegrateData(anchorset = seu_anchors, normalization.method = "SCT")
  DefaultAssay(seu_ref) = "integrated"
  # seu_ref     = RenameAssays(seu_ref, originalexp = "RNA")

  # Run the standard workflow for visualization and clustering
  # seu_ref     = SCTransform(seu_ref)
  # seu_ref     = ScaleData(seu_ref, verbose = FALSE)
  message('  doing umap')
  seu_ref     = RunPCA(seu_ref, npcs = n_dims, verbose = FALSE)
  seu_ref     = RunUMAP(seu_ref, reduction = "pca", dims = 1:n_dims, 
    return.model = TRUE)
  seu_ref     = FindNeighbors(seu_ref, reduction = "pca", dims = 1:n_dims)

  # convert to azimuth ref
  message('  making reference')
  azi_ref     = AzimuthReference(
    object      = seu_ref,
    refUMAP     = "umap",
    refDR       = "pca",
    refAssay    = "integrated",
    metadata    = c("cluster_id"),
    dims        = 1:n_dims,
    k.param     = 31,
    reference.version = "1.0.0"
  )
  saveRDS(object = azi_ref, file = azi_ref_f, compress = FALSE)
  SaveAnnoyIndex(object = azi_ref[["refdr.annoy.neighbors"]], 
    file = azi_annoy_f)
```

Thanks!
Will
