### ISSUE TITLE
issue with port to launch a container

### ISSUE THREAD

**Issue by turbo9001** [satijalab/azimuth#12]
Hello, I finished building the Docker image. The following command has always been no response. 
```
docker run -it -p 3838:3838 -v pbmc:/reference-data:ro azimuth
```
Tried the following as suggested and got invalid hostPort
```
docker run -it -p NNNN:3838 -v pbmc:/reference-data:ro azimuth
docker: Invalid hostPort: NNNN.
```
Any other suggestions? Thanks.

**Comment by andrewwbutler** [comment]
Hi,

What exactly do you mean by no response? Are you able to run the Azimuth outside of docker (i.e. `Azimuth::AzimuthApp()`) ? 

As per your second issue, `NNNN` was meant as a placeholder for a different port number (if 3838 was already in use). You shouldn't actually use `NNNN`.

**Comment by turbo9001** [comment]
This is what I got:
```
> Azimuth::AzimuthApp(reference='/reference-data')
Registered S3 method overwritten by 'cli':
  method     from    
  print.boxx spatstat
Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat
Attaching shinyBS
Loading required package: shiny

Listening on http://0.0.0.0:3838
```
And got no further response. I wasn't sure what other port to try, so just entered the Ns. I haven't yet tried running outside of docker as not sure if the installation will update Seurat library automatically?  I don't want to update it at the moment due to ongoing work.

**Comment by andrewwbutler** [comment]
This appears to be running. If you open a browser to the address listed there (http://0.0.0.0:3838), you should see the app.

**Comment by qys2007** [comment]
Tried it on both Chrome and Firefox, got: This site can’t be reached/Unable to connect

**Comment by turbo9001** [comment]
Tried it on both Chrome and Firefox, got: This site can’t be reached/Unable to connect

**Comment by mojaveazure** [comment]
You need to ensure that you're properly enabling port forwarding using the `-p` argument and specifying the full physical path to the reference data using the `-v` argument. For example, if your reference is in your `Downloads` directory, the full path will be `~/Downloads/pbmc`; omitting either argument will not allow Azimuth to launch properly in the Docker container

Example:

```bash
docker run -v ~/Downloads/pbmc:/reference-data -p 3838:38383
```

**Comment by turbo9001** [comment]
Thanks for the comment. As shown above, I specified both -p and -v in the initial command.  Now tried the command in your example with full path:

```
docker run -v ~/Downloads/azimuth/pbmc:/reference-data -p 3838:38383
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...] [flags]

Run a command in a new container
```
Also tried the initial command used by providing the full path:
```
docker run -it -p 3838:3838 -v ~/Downloads/azimuth/pbmc:/reference-data:ro azimuth
docker: Error response from daemon: driver failed programming external connectivity on endpoint trusting_chaum (a36b67f94d1bc6738483c1f57da9b10243e825ad6e4ee59a2a8b855626afb52e): Bind for 0.0.0.0:3838 failed: port is already allocated.
```

**Comment by andrewwbutler** [comment]
Hi,

For the first error, can you try adding the name of the image to the `docker run` command?

`docker run -v ~/Downloads/azimuth/pbmc:/reference-data -p 3838:38383 azimuth`

The second issue suggests that you already have a container running on that port (3838). If you see a previous azimuth container running, try killing and running again.

```
docker container ls
docker rm -f <container-name>
```

**Comment by turbo9001** [comment]
Thanks. It's helpful. Now I get this message back again:
```
> Azimuth::AzimuthApp(reference='/reference-data')
Registered S3 method overwritten by 'cli':
  method     from    
  print.boxx spatstat
Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat
Attaching shinyBS
Loading required package: shiny

Listening on http://0.0.0.0:3838
```
Just the above address still didn't give me anything in the browsers.

**Comment by andrewwbutler** [comment]
Sorry, it looks like an extra 3 was added by mistake to the ports in the command above. Try: 

`docker run -v ~/Downloads/azimuth/pbmc:/reference-data -p 3838:3838 azimuth`
