### ISSUE TITLE
How to solve Azimuth docker stuck at Warning: Error in : Cannot find 'ADT' in this Seurat object?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/azimuth#122]
Hi there, 

I failed to install Azimuth package due to error of the `presto` package (#121 #124). So I decided to use the Docker. 

I was successful at loading the reference and query data, but the terminal remained stuck at "Warning: Error in : Cannot find 'ADT' in this Seurat object" and the web port stuck at "Matching cell" for over 24 hours for only 20K query cells (which came from `SeuratDiet` of my existing Seurat object) with the human tonsil reference. 

Would you mind helping me solve this error?

Thank you so much!

Debug ID = 0e608222525b

<img width="1026" alt="Screen Shot 2022-09-19 at 1 51 32 PM" src="https://user-images.githubusercontent.com/62179082/191021418-52f33d00-362b-4a10-a4c8-3f5f8c97ece1.png">

<img width="853" alt="Screen Shot 2022-09-19 at 1 52 31 PM" src="https://user-images.githubusercontent.com/62179082/191021580-a7892539-c670-4384-b5e4-0716bdad1889.png">

**Comment by denvercal1234GitHub** [comment]
Saw that issue #96 reported this error. Will try and update soon.

**Comment by AustinHartman** [comment]
The tonsil reference does not contain the ADT counts, but the configuration of your reference is expecting the `ADT` assay to be present. You can toggle this setting by adding this line to your JSON configuration: `"Azimuth.app.do_adt": "FALSE"`

**Comment by denvercal1234GitHub** [comment]
Thank you Austin! Hopefully other omics will be incorporated soon in Azimuth? Thanks a great tool.
