### ISSUE TITLE
What happen to the data we upload to the App after the analysis is finished?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/azimuth#123]
Hi there, 

The web app seems great, but would you mind informing me what happens to the data we uploaded as query data to the web app? Will it get stored or analyzed or only temporarily used and will get destroyed at the end?

Thank you!

**Comment by AustinHartman** [comment]
Yup, the query data is only uploaded for the purpose of mapping and never held onto once the app is closed or used for any additional analysis.

**Comment by denvercal1234GitHub** [comment]
Thank you so much for the prompt response!
