### ISSUE TITLE
How to improve low (14% anchors identified) and (1.5/5 cluster preservation score)?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/azimuth#125]
Hi there, 

Thanks for a great and user-friendly tool. 

I obtained 13.7% of the query cells having anchors and only 1.43/5 cluster preservation score (`debug ID = 2d67b02e11a5`)

The info said this could be due to the high homogeneity of the query dataset. 

**Q1.** I will need to check the DEGs for the predicted cell type in my query cells as advised as the result. Does this mean I need to perform `FindMarkers()` on my own using the idents from the predicted cell types? If so, I will need to `SCTransform`/normalize the data (as Azimuth does not normalize query), `PrepSCTMarkers`, then `FindMarkers` using these predicted idents of my existing Seurat query object?

**Q2.** I uploaded the query data as RNA `counts` (unnormalized) for the mapping from my existing Seurat obj that had already gone through gene and cell filtering. The info page said not to do any filtering. Should I upload now instead directly the merged object of only raw `cellranger counts` output in order to improve these metrics?

Thank you so much for your patience and help.

**Comment by AustinHartman** [comment]
For the first question, that seems like a reasonable approach. It's always good to validate annotation results with known marker genes for the cell types of interest. You can first run `NormalizeData` on the Seurat object and then run `FindMarkers` between clusters/cell types of interest. For the second question, I'd be surprised if standard filtering altered results dramatically and it is likely best to exclude outlier cells from downstream analysis.

**Comment by denvercal1234GitHub** [comment]
Thank you Austin!
