### ISSUE TITLE
project qurey on reference UMAP

### ISSUE THREAD

**Issue by intawat** [satijalab/azimuth#134]
I made my own reference map using Azimuth (Thank you for develop this very good tool). Then use it for TransferData function, the results is very good as I expected. However, I have problem to visualize the result on reference Umap. I follow the code from an issue  https://github.com/satijalab/azimuth/issues/77.  RF =my reference map.

### Calculate the query neighbors in the reference with respect to the integrated embeddings.

 query[["query_ref.nn"]] <- FindNeighbors(
   object = Embeddings(RF[["refDR"]]),
   query = Embeddings(query[["integrated_dr"]]),
   return.neighbor = TRUE,
   l2.norm = TRUE )   

 ### The reference used in the app is downsampled compared to the reference on which the UMAP model was computed. This step, using the helper function NNTransform, corrects the Neighbors to account for the downsampling.
 
query <- Azimuth:::NNTransform(
   object = query,
   meta.data = RF[[]]
 )

### Project the query to the reference UMAP.

 query[["proj.umap"]] <- RunUMAP(
   object = query[["query_ref.nn"]],
   reduction.model = RF[["refUMAP"]],
   reduction.key = 'UMAP_'
 )

DimPlot(object = query, reduction = "proj.umap",label = TRUE) + NoLegend()

Then project map is not nice as below

<img width="552" alt="Screen Shot 2023-02-02 at 7 18 20 AM" src="https://user-images.githubusercontent.com/7950494/216335711-2bfea092-e38e-43f5-85b5-9c6557734555.png">

the REF map is below

<img width="496" alt="Screen Shot 2023-02-02 at 7 18 27 AM" src="https://user-images.githubusercontent.com/7950494/216335791-68da4ca8-97b9-41d5-9a5d-cc8dc23c793a.png">

# Please help

**Comment by Gesmira** [comment]
answered at [issue 6928](https://github.com/satijalab/seurat/issues/6928)
