### ISSUE TITLE
Human bone marrow reference 3rd level

### ISSUE THREAD

**Issue by NoemieL** [satijalab/azimuth#142]
Hi,

I am currently analyzing bone marrow (BM) samples and using Azimuth with the BM ref for cell classification. It works very well. I am interested in a deeper classification of cell subtypes as proposed in the PBMC level 3 reference. However, using both ref, I have found some inconsistencies such as cells classified as T cells by the BM ref and as erythrocytes by the PBMC repository. Would you consider providing a third level of annotation for the BM ref similar to the PBMC ref? If not, how do you handle these inconsistencies?

Thank you

**Comment by cathalgking** [comment]
Hi @NoemieL 
I would like to use the BM ref with my dataset but when I run the following command I get an error message saying it is not found. Did you get a similar error originally? Or how did you download the BM ref?

`there is no package called ‘bonemarrowref.SeuratData`

![Screen Shot 2023-04-14 at 9 49 11 am](https://user-images.githubusercontent.com/32261323/231910349-6112ea91-8e4c-4ee6-b907-33b6bf170fba.png)

The code I am running is:

`obj <- RunAzimuth(obj, reference = "bonemarrowref")`

Thanks

**Comment by Gesmira** [comment]
Hi @NoemieL, currently we do not have plans to add another level of annotation. For now, I would reccomend using the annotations from the bone marrow reference if your query is a bone marrow sample. Then, you can further subcluster and explore differentially expressed genes within the `celltype.l2` level if you are interested further levels of resolution. 

@cathalgking Make sure you have previously downloaded the reference with
```
library(SeuratData)
InstallData("bonemarrowref.SeuratData")
obj <- RunAzimuth(obj, reference = "bonemarrowref")
```

Hope that helps!
