### ISSUE TITLE
Cannot find 'refUMAP' error in Docker

### ISSUE THREAD

**Issue by athulmenon** [satijalab/azimuth#143]
Hi Team,

Thanks for this amazing tool.

I am trying to run azimuth 0.4.6 GUI using docker. My command is as below. 
 docker run -it -p 3872:3838 -v $PWD:/reference-data:ro satijalab/azimuth:0.4.6

The required human pbmc reference files are kept in the reference folder (https://seurat.nygenome.org/references/pbmc/). I am receiving the below error.

`> Azimuth::AzimuthApp(reference='/reference-data')
Registered S3 method overwritten by 'spatstat.geom':
  method     from
  print.boxx cli
Registered S3 method overwritten by 'SeuratDisk':
  method            from
  as.sparse.H5Group Seurat
Attaching shinyBS
Loading required package: shiny

Listening on http://0.0.0.0:3838
Warning: Error in : Cannot find 'refUMAP' in this Seurat object
  59: stop
  58: [[.Seurat
  54: LoadReference
  50: server
Error : Cannot find 'refUMAP' in this Seurat object`

Can you please comment on how to fix this? Thanks in advance.

Regards,
Athul

**Comment by Gesmira** [comment]
Hi Athul, 
It seems like that data you've linked is in an older format. I would recommend downloading the data from [here](https://zenodo.org/record/4546839#.ZD83_-zMJlk). Hope that helps!
