### ISSUE TITLE
@ChristineHOconnor since the `ConvertEnsembleToSymbol` gene is not currently exported from the seurat5 branch of Azimuth, use three colons rather than two access the function:

### ISSUE THREAD

**Issue by ChristineHOconnor** [satijalab/azimuth#146]
@ChristineHOconnor since the `ConvertEnsembleToSymbol` gene is not currently exported from the seurat5 branch of Azimuth, use three colons rather than two access the function:
`Azimuth:::ConvertEnsembleToSymbol(mat = OU_count.mat, species = "mouse")`

_Originally posted by @AustinHartman in https://github.com/satijalab/azimuth/issues/145#issuecomment-1500473705_
            
That option also errors out for me

`OU_count.mat <- Azimuth:::ConvertEnsembleToSymbol(mat = OU_count.mat, species = "mouse") 
Error: object 'ConvertEnsembleToSymbol' not found`

**Comment by Gesmira** [comment]
Hi, can you confirm that you have installed and loaded the seurat5 version of Azimuth?
```
remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE)
library(Azimuth)
```

**Comment by ChristineHOconnor** [comment]
Hi, yes, I used this command to install Azimuth: 

```remotes::install_github("satijalab/azimuth", "seurat5")```

I have version 0.4.6.9002 of Azimuth and version 4.9.9.9042 of Seurat installed.

**Comment by aCompanionUnobtrusive** [comment]
I am also having this issue... has anyone been able to solve this?
I have version ‘4.9.9.9042’ of Seurat and version ‘0.4.6’ of Azimuth.

**Comment by Gesmira** [comment]
Hi, @aCompanionUnobtrusive, looks like you're not using the seurat5 version of Azimuth. As mentioned above, you can install and load it using: 
```
remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE)
library(Azimuth)
```

**Comment by Gesmira** [comment]
Great! 

@ChristineHOconnor, can you confirm if you are still having the error?

**Comment by Kexin118** [comment]
Hi @ChristineHOconnor, I have the same issue as yours. 

I have version 0.4.6.9002 of Azimuth and version 4.9.9.9042 of Seurat installed. The Azimuth was installed by remotes::install_github("satijalab/azimuth", "seurat5").

Can I ask how did you solve the problem?

**Comment by Gesmira** [comment]
Hi @Kexin118, can you try restarting your R session and attempting to install and call the function again? It's possible you had an older version of Azimuth loaded in previously and it is interfering.

**Comment by Kexin118** [comment]
Hi @Gesmira, it works! Thank you so much!!

**Comment by PerkyTussellop** [comment]
> Hi, I'm no longer having this error and I'm able to run Azimuth:::ConvertEnsembleToSymbol

I am not able to run ConvertEnsembletoSymbol. Oddly, I'm not getting any error with simply entering:
library(Azimuth)

However, I must presume Azimuth is not installed correctly, as I can't find it otherwise. Trying: remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE)
just gives non-zero exit status messages or "Error: object 'FindBridgeTransferAnchors' is not exported by 'namespace:Seurat'", depending on.. who knows...
