### ISSUE TITLE
liver reference Zenodo link error

### ISSUE THREAD

**Issue by mzz92** [satijalab/azimuth#147]
I'd like to run liver data annotation on a local machine and am trying to install the liver reference file. However, the Zenodo link seems to be broken from the references page (https://azimuth.hubmapconsortium.org/references/). Is there another way to obtain the liver reference set?

I've also tried updating my SeuratData library, but do not see liverref with AvailableData().

Thanks!

**Comment by Gesmira** [comment]
Hi, thanks for reporting this! You can download it here for now: https://zenodo.org/record/7770308#.ZD8DAezMJlk 
We'll fix that soon.

**Comment by Gesmira** [comment]
You would save the `ref.Rds` and `idx.annoy` in a folder (for example: `~/liver_reference`). Then you would call the RunAzimuth function with your query like so: 
`query <- RunAzimuth(query, reference = "~/liver_reference)`
