### ISSUE TITLE
How to use my own RNA-seq as reference for "RunAzimuth"?

### ISSUE THREAD

**Issue by yingsun-ucsd** [satijalab/azimuth#150]
I used Seurat for my image-based spatial data from nanostring. It works great. Instead of performing unsupervised analysis, I followed the instructions to map the profiles to Azimuth Human Pancreas reference as "pancreas.object <- RunAzimuth( pancreas.object, reference = "pancreasref" )" Thanks for [@AustinHartman](https://github.com/AustinHartman)'s help.

Now I would like to do the same thing **with my own single-cell RNA-seq data as the reference**. To my understanding, I can use "AzimuthReference" to generate the reference to do so. But I did not find the instruction, protocol, or example of how. I am very new to Seurat, could you please give me some guidance on it? Thanks a lot!

**Comment by Gesmira** [comment]
Hi, 
You can find info for generating your own AzimuthReference [here](https://github.com/satijalab/azimuth/wiki/Generating-an-Azimuth-Reference)

**Comment by yingsun-ucsd** [comment]
Thank you @Gesmira 

But there is no detailed info about how to use it. I am very new to Azimuth, can you let me know where I can get more information or even may some examples? Thanks again.
