### ISSUE TITLE
Files not present for ATAC mapping

### ISSUE THREAD

**Issue by ollieeknight** [satijalab/azimuth#151]
Heya,

Using [this](https://satijalab.github.io/azimuth/articles/run_azimuth_tutorial.html#scatac-seq-queries) vignette for mapping scATAC, I get an error that the `ref.Rds` and `annoy.idx `files are missing. Upon downloading the Rds from [here](https://zenodo.org/record/7770374#.ZB91X-zMJlk), it appears the `annoy.idx` is still missing. I'm not sure which dimensionality reductions are alright to map this using `AzimuthReference`, either. Do you have extra guidance, or could upload the `annoy.idx`?

Thanks a million

Ollie

**Comment by Gesmira** [comment]
Hi, for Azimuth ATAC, make sure you have the v5 version of Azimuth installed and that you are running `RunAzimuth` with `query.modality = ATAC`. Azimuth ATAC doesn't use the same format as regular Azimuth for RNA. All `RunAzimuth` needs for the reference is the 'ext.rds' file which you downloaded at that link. 

You can also find more info about the AzimuthReference format here: [https://github.com/satijalab/azimuth/wiki/Azimuth-Reference-Format](https://github.com/satijalab/azimuth/wiki/Azimuth-Reference-Format)

**Comment by ollieeknight** [comment]
yes, you're totally right! I was trying to run it on an assay called MACS2. Thanks!
