### ISSUE TITLE
Using ATAC-bridge in RunAzimuth()

### ISSUE THREAD

**Issue by dy-lin** [satijalab/azimuth#152]
Is there a way to obtain celltype labels for an ATAC human bonemarrow dataset using RunAzimuth()? Is there an ATAC-bridge reference in SeuratData?

Or does a custom reference have to be built using the h5ad files (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE194122)?

**Comment by Gesmira** [comment]
Hi, 
We haven't uploaded the ATAC references to SeuratData yet, but you can use the Azimuth web app or find the bone marrow reference [here](https://zenodo.org/record/7770389#.ZFhDx-zMLHo) to download and run locally in R with RunAzimuth().

**Comment by dy-lin** [comment]
Is the `idx.annoy` file the same as the one for RNA? https://zenodo.org/record/5521512#.ZGPHyXbMKJE

**Comment by dy-lin** [comment]
Using that `idx.annoy`, I get:
```
> list.files()
[1] "idx.annoy" "ref.Rds"  
> atac.ref <- RunAzimuth(
+     atac,
+     reference = "."
+ )
Error: Cannot find 'refdr.annoy.neighbors' in this Seurat object
```

**Comment by dy-lin** [comment]
My scATAC-seq object is an integrated object (integrated using `IntegrateEmbeddings()`). Is it advisable to just `cat` the fragment files for the samples that have been integrated?

**Comment by dy-lin** [comment]
After some manipulation of each individual atac fragments file to match the barcode names to the integrated object (i.e. `${sample_name}_${barcode}`), I'm unable to run `tabix` on the fragments file.
