### ISSUE TITLE
RunAzimuth() error: Error in curl::handle_setopt(handle, .list = req$options) :

### ISSUE THREAD

**Issue by aaronwolf1995** [satijalab/azimuth#156]
In learning tutorial of Integrative analysis in Seurat v5 (https://satijalab.org/seurat/articles/seurat5_integration.html):
  I have followed instructions for "seurat5" version installing of Azimuth and other packages, as it has mentioned.
  However, when I came to this line:

obj <- RunAzimuth(obj,reference = "pbmcref")

It went error as it follows:

Error in curl::handle_setopt(handle, .list = req$options) : 
  A libcurl function was given a bad argument
In addition: Warning message:
In curl::handle_setopt(handle, .list = req$options) :
  NAs introduced by coercion to integer range

First I thought it might be because of the reference, so I changed to another reference (lungref, e.g.), but it did not work.
Secondly I changed Azimuth to older version by :  remotes::install_github('satijalab/azimuth')
It was running into another error and still did not work (error is the same as reference for RunAzimuth() #154)

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if the issue persists.

**Comment by vandontduong** [comment]
I've ran into the same issue. I have internet connection, as I'm connected through my university's compute cluster (SLURM-based).

```
obj <- RunAzimuth(obj, reference = "pbmcref")
Using cached data manifest, last updated at 2023-09-25 16:01:26
Using cached data manifest, last updated at 2023-09-25 16:01:26
Using cached data manifest, last updated at 2023-09-25 16:01:26
Using cached data manifest, last updated at 2023-09-25 16:01:26
Warning: Overwriting miscellanous data for model
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL connect error
```
