### ISSUE TITLE
How to build CITE-Seq Azimuth reference?

### ISSUE THREAD

**Issue by frankligy** [satijalab/azimuth#163]
Hello,

Thanks again for the great tools, I wonder if there are any instructions on how to build a CITE-Seq reference? Based on my understanding, the process of building CITE-Seq reference should be slightly different from RNA reference which has been documented here (https://github.com/satijalab/azimuth/wiki/Azimuth-Reference-Format), I assume generally:

[1] After running WNN, we need to run sPCA to derive the sPCA embedding
[2] Then we need to use the sPCA as `refDR`

But still, I am sure there are a lot of subtleties underlying that I might miss, so would it be possible to share some instructions on that?

Thanks in advance,
Frank

**Comment by longmanz** [comment]
Hi, 
Please refer to this [vignette](https://satijalab.org/seurat/articles/multimodal_reference_mapping#example-2-mapping-human-bone-marrow-cells) for building a WNN reference.
