### ISSUE TITLE
Reference for azimuth PBMC reference

### ISSUE THREAD

**Issue by neanderthalensis** [satijalab/azimuth#164]
The azimuth /references site cites Hao and Hao et al. as a source for the PBMC dataset. I believe that this is referring to the 2020 Hao et al (DOI: 0.1101/2020.10.12.335331) paper on biorxiv (which seems to have been later published as DOI: 0.1016/j.cell.2021.04.048). However the link points to Stuart et al. paper in cell (DOI: 10.1016/j.cell.2019.05.031).

**Comment by Gesmira** [comment]
Fixed now, thank you!
