### ISSUE TITLE
Azimuth install fails: SeuratDisk not available

### ISSUE THREAD

**Issue by rhart604** [satijalab/azimuth#165]
Trying to install everything for Seurat5, I got an error during the installation of Azimuth:

ERROR: dependency 'SeuratDisk' is not available for package 'Azimuth'
* removing 'D:/library/Azimuth'

Session info below:
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.8.2    compiler_4.3.1    R6_2.5.1          rprojroot_2.0.3   cli_3.6.1         prettyunits_1.1.1 tools_4.3.1      
 [8] rstudioapi_0.15.0 curl_5.0.1        crayon_1.5.2      remotes_2.4.2.1   desc_1.4.2        callr_3.7.3       ps_1.7.5         
[15] pkgbuild_1.4.2   
>

**Comment by Gesmira** [comment]
Hi, 
Have you tried installing SeuratDisk before Azimuth install? 
`remotes::install_github("mojaveazure/seurat-disk")`

**Comment by rhart604** [comment]
I had previously followed the installation instructions and used this:
remotes::install_github<https://remotes.r-lib.org/reference/install_github.html>("satijalab/seurat-data", "seurat5", quiet = TRUE)

But using your install command instead works, and then after that, Azimuth installs correctly.

Thanks.

**Comment by Gesmira** [comment]
Ok great!

**Comment by mmokrejs** [comment]
Please reopen this issue and get fixed at least the documentation at https://satijalab.org/seurat/articles/install 
It does not even mention one needs to install `SeuratDisk`. I just hit this very same issue as well.

```
> remotes::install_github("satijalab/azimuth", "seurat5", quiet = FALSE)
Downloading GitHub repo satijalab/azimuth@seurat5
Skipping 1 packages not available: SeuratDisk
Running `R CMD build`...
* checking for file '/auto/vestec1-elixir/projects/biocev/mmokrejs/tmp/Rtmpb9MqpN/remotes9a4683d83441e/satijalab-azimuth-3d78d3f/DESCRIPTION' ... OK
* preparing 'Azimuth':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted 'LazyData' from DESCRIPTION
* building 'Azimuth_0.4.6.9004.tar.gz'
ERROR: dependency 'SeuratDisk' is not available for package 'Azimuth'
* removing '/auto/vestec1-elixir/projects/biocev/gentoo/usr/lib64/R/library/Azimuth'
Warning message:
In i.p(...) :
  installation of package '/storage/vestec1-elixir/projects/biocev/mmokrejs/tmp/Rtmpb9MqpN/file9a4687ac0868d/Azimuth_0.4.6.9004.tar.gz' had non-zero exit status
> 
```

**Comment by mmokrejs** [comment]
`remotes::install_github("mojaveazure/seurat-disk")`

**Comment by Gesmira** [comment]
Hi @mmokrejs SeuratDisk is not required for Seurat v5 install so we won't be updating the documentation at the link you included. The dependency has been added back into the Azimuth (seurat5) package, so it should automatically install when you install Azimuth from now on. And, yes, that is the way to install SeuratDisk regularly which I had included in my answer above.

**Comment by Projectnix** [comment]
Hi @Gesmira 

Just letting you know now that the Seurat5 branch of Azimuth fails to update/install because it now requires the Seurat5 branch of seurat-disk, which does not exist yet on github.
