### ISSUE TITLE
Azimuth installation error

### ISSUE THREAD

**Issue by JarodMR1** [satijalab/azimuth#169]
Hi, I'm rather new to using R and am having troubles with installing the Azimuth package. Both seurat and seurat-data seemed to install perfectly fine when. using the following code:

devtools::install_github("satijalab/seurat", "seurat5")
devtools::install_github("satijalab/seurat-data", "seurat5")
devtools::install_github("satijalab/azimuth", "seurat5")

However, upon rstudio attempting to install the azimuth package I get the error posted below (non-zero exit status?). Any help would be appreciated. 

devtools::install_github("satijalab/azimuth", "seurat5")
Downloading GitHub repo satijalab/azimuth@seurat5
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: rmarkdown (2.23  -> 2.24 ) [CRAN]
5: curl      (5.0.1 -> 5.0.2) [CRAN]
6: ggplot2   (3.4.2 -> 3.4.3) [CRAN]
7: patchwork (1.1.2 -> 1.1.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
rmarkdown (2.23  -> 2.24 ) [CRAN]
curl      (5.0.1 -> 5.0.2) [CRAN]
ggplot2   (3.4.2 -> 3.4.3) [CRAN]
patchwork (1.1.2 -> 1.1.3) [CRAN]
Installing 4 packages: rmarkdown, curl, ggplot2, patchwork
trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/rmarkdown_2.23.tgz'
Content type 'application/x-gzip' length 2607038 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/curl_5.0.1.tgz'
Content type 'application/x-gzip' length 811275 bytes (792 KB)
==================================================
downloaded 792 KB

trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/ggplot2_3.4.2.tgz'
Content type 'application/x-gzip' length 4304248 bytes (4.1 MB)
==================================================
downloaded 4.1 MB

trying URL 'http://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/patchwork_1.1.2.tgz'
Content type 'application/x-gzip' length 3240686 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

The downloaded binary packages are in
	/var/folders/w4/5pk1jzq55rbdww3dz5wykrz00000gn/T//RtmpPrnCY7/downloaded_packages
── R CMD build ─────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/w4/5pk1jzq55rbdww3dz5wykrz00000gn/T/RtmpPrnCY7/remotes18d7dd833e7/satijalab-azimuth-955e4b9/DESCRIPTION’ (428ms)
─  preparing ‘Azimuth’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘Azimuth_0.4.6.9004.tar.gz’
   
* installing *source* package ‘Azimuth’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
using C++11
using SDK: ‘MacOSX13.3.sdk’
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c csc_to_csr.cpp -o csc_to_csr.o
clang++ -arch x86_64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/x86_64/lib -o Azimuth.so RcppExports.o csc_to_csr.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/00LOCK-Azimuth/00new/Azimuth/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Signac'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘Azimuth’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Azimuth’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/w4/5pk1jzq55rbdww3dz5wykrz00000gn/T//RtmpPrnCY7/file18d7524ebc66/Azimuth_0.4.6.9004.tar.gz’ had non-zero exit status

> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] miniUI_0.1.1.1    compiler_4.3.1    crayon_1.5.2      promises_1.2.1   
 [5] Rcpp_1.0.11       stringr_1.5.0     callr_3.7.3       later_1.3.1      
 [9] fastmap_1.1.1     mime_0.12         R6_2.5.1          curl_5.0.1       
[13] htmlwidgets_1.6.2 desc_1.4.2        profvis_0.3.8     rprojroot_2.0.3  
[17] shiny_1.7.5       rlang_1.1.1       cachem_1.0.8      stringi_1.7.12   
[21] httpuv_1.6.11     fs_1.6.3          pkgload_1.3.2.1   memoise_2.0.1    
[25] cli_3.6.1         magrittr_2.0.3    ps_1.7.5          digest_0.6.33    
[29] processx_3.8.2    rstudioapi_0.15.0 xtable_1.8-4      remotes_2.4.2.1  
[33] devtools_2.4.5    lifecycle_1.0.3   prettyunits_1.1.1 vctrs_0.6.3      
[37] glue_1.6.2        urlchecker_1.0.1  sessioninfo_1.2.2 pkgbuild_1.4.2   
[41] purrr_1.0.2       usethis_2.2.2     tools_4.3.1       ellipsis_0.3.2   
[45] htmltools_0.5.6

**Comment by PerkyTussellop** [comment]
Similar issues. On M1 Mac here OS 13.5,

**Comment by Gesmira** [comment]
Closing now due to lack of response. Feel free to reopen if the issue persists.
