### ISSUE TITLE
Proposal: update tonsil atlas reference and include new ref in Azimuth-ATAC

### ISSUE THREAD

**Issue by massonix** [satijalab/azimuth#171]
Hi @satijalab!

Thanks for developing this great tool, which makes it very easy to annotate new single-cell datasets.

I'm the first author of the paper [An Atlas of Cells in the Human Tonsil](https://www.biorxiv.org/content/10.1101/2022.06.24.497299v1), which was recently accepted for publication. During the revision process, we included 7 additional donors, almost doubled the number of cells in the atlas, and sharpened the annotation. I'm in the process of curating the final datasets to upload them to [Zenodo](https://zenodo.org/record/6340174). Once that's done, could you please update the Azimuth reference? I will be delighted to work together on it, particularly in defining the proper annotation.

Also, I will upload a Seurat object with the scATAC-seq data and annotation for each cell, which I believe could be a great addition to Azimuth-ATAC. What do you think? Any ideas on how to format the final object to make it easier to upload to Azimuth will be greatly appreciated.

Let me know your thoughts!

Ramon

**Comment by Gesmira** [comment]
Hi @massonix, 
Thanks for reaching out! We would be happy to work with you to update the reference and discuss a potential Azimuth ATAC reference. We're a bit busy at the moment with the Seurat5 release so are less active on this page, but if you email me gmolla@nygenome.org we can keep in touch that way.

**Comment by massonix** [comment]
Great, thanks @Gesmira ! I will reach out once I have everything in Zenodo.

Best of luck  with Seurat5, we're all looking forward to it!!
