### ISSUE TITLE
Error in installing Azimuth 

### ISSUE THREAD

**Issue by dzhao98** [satijalab/azimuth#181]
Hi everyone: 

I am trying to install Azimuth following the vignette here https://satijalab.github.io/azimuth/articles/run_azimuth_tutorial.html
While running  ```devtools::[install_github](https://remotes.r-lib.org/reference/install_github.html)("satijalab/azimuth", "seurat5")```
this is the error that I have 
```Error: object 'FindBridgeTransferAnchors' is not exported by 'namespace:Seurat'
Execution halted
ERROR: lazy loading failed for package ‘Azimuth’
* removing ‘/vast/palmer/home.mccleary/dz369/.conda/envs/seurat/lib/R/library/Azimuth’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpgKfSd2/file2f4554b87a6e2/Azimuth_0.4.6.9004.tar.gz’ had non-zero exit status 
```
I have seurat v 4.4.0 installed it seems like FindBridgeTransferAnchors is not a function anymore?

**Comment by mikalelh** [comment]
I seem to be getting the same error: 

“installation of package ‘/tmp/RtmpgnJF3P/file42cbfee5947/SeuratDisk_0.0.0.9020.tar.gz’ had non-zero exit status”. 

Just wondering how I could go about installing the package.

Thanks in advance for your help!

**Comment by dzhao98** [comment]
> I seem to be getting the same error:
> 
> “installation of package ‘/tmp/RtmpgnJF3P/file42cbfee5947/SeuratDisk_0.0.0.9020.tar.gz’ had non-zero exit status”.
> 
> Just wondering how I could go about installing the package.
> 
> Thanks in advance for your help!
Hey I tried on the github page and it works 
remotes::install_github('satijalab/azimuth', ref = 'master'
