### ISSUE TITLE
error with install azimuth

### ISSUE THREAD

**Issue by turuilin** [satijalab/azimuth#187]
when l tried to install azimuth, error has occurred:

remotes::install_github('satijalab/azimuth', ref = 'master')
Using github PAT from envvar GITHUB_TOKEN
Downloading GitHub repo satijalab/azimuth@master
Error: Failed to install 'Azimuth' from GitHub:
  HTTP error 404.
  No commit found for the ref seurat5

  Did you spell the repo owner (`stuart-lab`) and repo name (`signac`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by alexQiSong** [comment]
Same issue here. Did you manage to find a solution?

**Comment by Jacobog02** [comment]
Same Issue as well. 
Attempted to install Signac by `install.packages("Signac")` and `remotes::install_github("staurt-lab/signac, ref = "develop")` 
Appears to be due to 2 days ago timoast removed the seurat5 branch see R-CMD-check #474 commit c05e583 in the Signac repo

**Comment by Jacobog02** [comment]
> Same Issue as well. Attempted to install Signac by `install.packages("Signac")` and `remotes::install_github("staurt-lab/signac, ref = "develop")` Appears to be due to 2 days ago timoast removed the seurat5 branch see R-CMD-check #474 commit c05e583 in the Signac repo

I fixed the issue by forking the Azimuth repo and removing `@seurat5` from line 29 in `DESCRIPTION` and I have verified the installation now works.
@turuilin  @alexQiSong I recommend you do the same until the fix gets pushed OR feel free to install my fork via `remotes::install_github("Jacobog02/azimuth_stopgap")`

**Comment by mihem** [comment]
same here. maybe @Gesmira for this quick fix?

**Comment by Gesmira** [comment]
Hi all, 
Thank you for bringing this to my attention! The master branch of Azimuth is now updated to install directly from the newest version of Signac on CRAN.

**Comment by ClarisseGanier** [comment]
I fixed it by installing "BSgenome.Hsapiens.UCSC.hg38" separately using :
 if (!require("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
