### ISSUE TITLE
Azimuth UMAP result is not consistent with Seurat

### ISSUE THREAD

**Issue by tewengtong** [satijalab/azimuth#201]
Dear author:I used Seurat to do normalized-->Find HVG --> scale the data --> Run PCA -- > Find neighbors and clusters --> Run UMAP. And then I run "RunAzimuth" to annotate my result. 

I have two questions: 1) Do I need to perform those steps before I use azimuth annotation? 2) Why is the UMAP result of Azimuth quite different from the UMAP result of Seurat? Which one should I use or consider the correct one? For example, the endothelial cells are clustered with pericyte in azimuth UMAP but they are separate from each other in the result of Suerat UMAP?

Thank you!

**Comment by tewengtong** [comment]
Just to elaborate on point 2: the annotation UMAP plots from Azimuth and Seurat both come from the azimuth annotation result. 
1) Seurat:  DimPlot(Seurat_object,reduction = "umap", group.by = "predicted.celltype.l1")
2) Azimuth:  DimPlot(Seurat_object,reduction = "umap.ref", group.by = "predicted.celltype.l1")

These two plots vary a lot.

**Comment by Gesmira** [comment]
Hi, 
The UMAPs are representing entirely different things: 

- The Seurat `RunUMAP()` output is created in an unsupervised manner and thus is only representative of the heterogeneity of your data.
- The Azimuth "umap.ref" is created by projecting your query data onto the reference object's UMAP. 

I would use the unsupervised UMAP as this can piece out the heterogeneity of your data better. You should still use the azimuth annotations, but the "umap.ref" will be representative of the low dimensional space of the reference and thus is not necessarily the best way to capture your object.
