### ISSUE TITLE
RunAzimuth not working with SCT assay

### ISSUE THREAD

**Issue by anoop1988** [satijalab/azimuth#203]
Hi,
when I run RunAzimuth() using seurat object with default assay "SCT" (I did SCTransfrom the object prior to Azimuth) the process running into error as below,
```
HIV_No_Doublet <- RunAzimuth(HIV_No_Doublet, reference = "pbmcref",assay = "SCT")
error below,
Finding anchors
Error in indices.ba[neighbors.ab, 1:k.anchor, drop = FALSE] : 
  subscript out of bounds
```
 But it is running properly a if I change the default assay "RNA".  So Azimuth will not work with SCTransformed data?

**Comment by Gesmira** [comment]
Hi, 
Azimuth does the preprocessing on the raw query data directly. It uses the SCTransform internally, thus you should not use the "SCT" assay. By default, we use the "RNA" assay to get the raw counts and then they will be SCTransformed as part of the preprocessing.

**Comment by Happier-CODE** [comment]
hI,when I run RunAzimuth() using seurat object with default assay "SCT" (I did SCTransfrom the object prior to Azimuth) the process running into error as below,

![Image](https://github.com/user-attachments/assets/dd389a3f-1f3a-46bf-a0a0-e36ebf0ea401)
