### ISSUE TITLE
Docker image tag says "v0.5.0" but sessionInfo() inside the container returns "Azimuth_0.4.6"

### ISSUE THREAD

**Issue by sinanassiri** [satijalab/azimuth#209]
Dear Azimuth team,

Could you please check that the docker image of v0.5.0 includes the correct release version? When pulling v0.5.0 (docker pull satijalab/azimuth:0.5.0), sessionInfo() returns "Azimuth_0.4.6.9004" inside the container.

Thanks,
Sina

**Comment by Gesmira** [comment]
Hi @sinanassiri, 
The functionality should be the same, we just built the docker image right before the release. We are releasing Seurat 5.0.2 shortly and will put out a new docker image for Azimuth too at that time.
