### ISSUE TITLE
Using Personal Reference

### ISSUE THREAD

**Issue by bloughstephen** [satijalab/azimuth#21]
When using my own reference and query datasets with Azimuth, when I load them and map cells to reference, it immediately crashes and I get this error:
Warning: Error in [[: subscript out of bounds
  78: eval
  77: eval
  76: withProgress
  75: observeEventHandler
   4: runApp
   1: Azimuth::AzimuthApp

I'm not sure why this happens as there doesn't seem like there is any instance where I would be indexing out of bounds?

**Comment by andrewwbutler** [comment]
Hi,

We will have more information on how to generate your own Azimuth references in the near future. For now, I would recommend using Seurat directly for mapping. Check out the vignettes ([link](https://satijalab.org/seurat/articles/integration_mapping.html), [link](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html)) for examples.

**Comment by andrewwbutler** [comment]
Just following up on this, in the latest version of Azimuth (v0.3.0) we provide the `AzimuthReference` function which can be used to generate the required reference format from an existing Seurat object for use with Azimuth. For details, you can checkout the [wiki](https://github.com/satijalab/azimuth/wiki/Azimuth-Reference-Format) and see examples in this [repo](https://github.com/satijalab/azimuth-references) (namely the export scripts - e.g. [here](https://github.com/satijalab/azimuth-references/blob/master/human_motorcortex/scripts/export.R)).

**Comment by Daisy-Chilin** [comment]
Hi, is there an update on using our own personal reference with Azimuth? Im currently using Azimuth_0.5.0, however, Im having issues. Any guidance would be greatly appreciated.
