### ISSUE TITLE
Azimuth and integrated data

### ISSUE THREAD

**Issue by tirk999** [satijalab/azimuth#210]
Hello everyone!

I want to use Azimuth to annotate two datasets that I have, by using a modified RunAzimuth() function (I had to adapt it to small datasets). 
Each dataset corresponds to a different replicate of the same experiment. 
As far as I know, Azimuth works with the "counts" slot of the RNA assay. Therefore, I assume that I cannot use the "integrated" assay to use Azimuth, in case I have one. Anyway, I am working with Harmony, which does not create an integrated assay. When  I try to run my function with the integrated assay obtained by Seurat integration, I indeed obtain this error.
`Error in h(simpleError(msg, call)) : 
error in evaluating the argument 'x' in selecting a method for function 'colSums': no 'dimnames' attribute for array`
My first question is: 
1. Is it correct to always use the RNA assay when I run Azimuth?

When coming to wanting to label both datasets,
2. Should I run Azimuth on each dataset separately  or
3. Should I merge the data (not integration) and run Azimuth on the "RNA" assay of the merged data?
4. Moreover, I understand that Azimuth applies SCT so I suppose there is no need for LogNorm or SCT normalization before running Azimuth. Is this correct?
Thank you a lot.

**Comment by Gesmira** [comment]
1. Yes, you should run Azimuth on the RNA assay with unnormalized data, as the app will normalize the data. 
2 and 3. This is up to you, we don't have a clear recommendation for this, but it should give similar results either way. 
4. Correct, you do not need to normalize your data before running Azimuth.
