### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by pwmellors** [satijalab/azimuth#213]
Hello,

When running Azimuth locally in R, e.g:

pbmcsca <- [RunAzimuth](https://satijalab.github.io/azimuth/reference/RunAzimuth.html)(pbmcsca, reference = "pbmcref")

Can one assume if the Azimuth package version is the same that the annotations will be reproducible? In other words, are changes made to databases on an ongoing basis, such that annotations may change over time?

Thank you

**Comment by anglixue** [comment]
Hi @Gesmira,
I met the same situation that the Azimuth annotation was different from a previous run. I found this on the webpage,

> If you have previously uploaded your data to - we recommend re-mapping your data with the latest version at [azimuth.hubmapconsortium.org](https://azimuth.hubmapconsortium.org/). The updated version includes the following new features:

> - Reference datasets are available for four organs
> - Improved mapping results, particularly when the query dataset represents a subset of the reference diversity (i.e. mapping sorted T cells onto the PBMC reference)
> - Interactive plots and visualizations
> - Ability to annotate cells at multiple levels of resolution/granularity
> - New QC metrics (replacing the previous pseudobulk correlation test)


I wonder if the difference is due to algorithm or just the change of the reference?

Thank you very much!

**Comment by Gesmira** [comment]
Hi, 
Within the same versions of Seurat and Azimuth, the annotations will stay the same as long as the same reference dataset is being used. The references are not changed very often, and the dates the references were last updated can be seen on the zenodo pages linked on the [azimuth website](https://azimuth.hubmapconsortium.org/references/). Version updates shown here are also generally small fixes and thus the annotations may still be the same between the versions. Thus, generally, using the call that @pwmellors is running, the annotations will stay the same with the same package versions.
