### ISSUE TITLE
object 'mtx.shape' not found ERROR Azimuth web app 

### ISSUE THREAD

**Issue by anastamag** [satijalab/azimuth#215]
Hi! 

When I upload my .h5ad file(pre-processed, <1Gb and <100.000 cells) to the Azimuth web app,  I get the error :object 'mtx.shape' not found. I am not sure what it refers to. Any suggestions? 

Thank you!

**Comment by Gesmira** [comment]
Hi @anastamag, 
I'm not immediately sure why you are seeing this error with file upload, but it seems to be failing in the LoadMetadata() function when trying to identify the shape of the matrix: https://github.com/satijalab/azimuth/blob/243ee5db80fcbffa3452c944254a325a3da2ef9e/R/helpers.R#L529

Is there anything unusual about the way you created this object? Another option would be to email me a small version of the object so I could try to troubleshoot.

**Comment by Gesmira** [comment]
Closing for now due to lack of response. Feel free to reopen if you continue to run into the issue.
