### ISSUE TITLE
Azimuth installation problem

### ISSUE THREAD

**Issue by bebejhun** [satijalab/azimuth#221]
I am encountering this error when I try to download the Azimuth.

Warning: downloaded length 21789259 != reported length 731245539Warning: URL 'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.16/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.5.tar.gz': Timeout of 60 seconds was reachedError in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://bioconductor.org/packages/3.16/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.5.tar.gz' failed
Warning: download of package 'BSgenome.Hsapiens.UCSC.hg38' failed── R CMD build

Then, I tried to install first the BSgenome however I also get an error for this.

BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")

Warning: downloaded length 74545739 != reported length 731245539Warning: URL 'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.16/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.5.tar.gz': Timeout of 300 seconds was reachedError in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://bioconductor.org/packages/3.16/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.5.tar.gz' failed
Warning: download of package 'BSgenome.Hsapiens.UCSC.hg38' failed

Does anyone here know how to solve this problem?
Thanks in advance.

**Comment by Gesmira** [comment]
Hi @bebejhun. 
Have you tried the solution [here](https://support.bioconductor.org/p/p133518/)?

**Comment by bebejhun** [comment]
@Gesmira yep I already solved it. Thanks !
