### ISSUE TITLE
Kidney reference zenodo

### ISSUE THREAD

**Issue by KalinNonchev** [satijalab/azimuth#223]
Hi,
thank you for maintaining this package. 

the Zenodo reference for the kidney dataset is not pointing to the newest version from https://github.com/satijalab/azimuth/issues/161. The version https://zenodo.org/records/5181818 has an issue with the preprocessing step. It works with the newer version: https://zenodo.org/records/10694842, but one should be aware of it. Also, the label names on the website for the different prediction levels should be updated (predicted.annotation.l3 instead of annotation.l3)...

Best,

**Comment by Gesmira** [comment]
Hi @KalinNonchev, 
Thanks for pointing out that we didn't update the Zenodo link! I have just gone ahead and fixed this. 
To your second point, are you referring to the Annotation Details for the reference [here](https://azimuth.hubmapconsortium.org/references/#Human%20-%20Kidney)? The `predicted.` prefix is used for the query dataset metadata columns when the query is mapped to the reference, but the reference levels are of the annotation.l3 format.

**Comment by KalinNonchev** [comment]
you are right, thanks
