### ISSUE TITLE
Bug in cells.use in template.R

### ISSUE THREAD

**Issue by twfs** [satijalab/azimuth#27]
Hi Folks, thanks for the great app. I was looking at the download template feature in the app which is a great idea. Looking at the code I noticed that unlike in the actual code the template seems to have a small bug where cells.use is set for mitochondrial gene filtered cells - the mito filter section will reset the cell.use rather than & it to the preceding feature and counts filters. The correct code is in the actual app but the template has the error:

```
# If the query contains mitochondrial genes, filter cells based on the
# thresholds for ${mito.key} you set in the app
if ("${mito.key}" %in% c(colnames(x = query[[]]))) {
  cells.use <- query[["${mito.key}", drop = TRUE]] <= ${mito.max} &
    query[["${mito.key}", drop = TRUE]] >= ${mito.min}
}

```
Thought I'd mention it. 

Thanks,

Tim

**Comment by andrewwbutler** [comment]
Hi Tim,

Thanks for mentioning. This should be fixed now in the master branch.

**Comment by twfs** [comment]
Great thanks Andrew!
