### ISSUE TITLE
labeled single cell type reference data

### ISSUE THREAD

**Issue by cornhundred** [satijalab/azimuth#36]
Hi, is it possible to download the cell metadata for the reference data (https://atlas.fredhutch.org/nygc/multimodal-pbmc/) used to build Azimuth? I downloaded the data from the multimodal-pbmc website, but the multi.h5seurat object does not appear to have cell metadata (e.g. cell types for each cell). Can this data and cell type metadata be obtained directly from Seurat?

**Comment by andrewwbutler** [comment]
Hi,

The celltype metadata should be available in that object as `celltype.l1(2/3)`.

```R
library(Seurat)
library(SeuratDisk)
ref <- LoadH5Seurat(file = "pbmc_multimodal.h5seurat")
colnames(ref[[]])
colnames(ref[[]])
[1] "nCount_ADT"   "nFeature_ADT" "nCount_RNA"   "nFeature_RNA" "orig.ident"  
[6] "lane"         "donor"        "time"         "celltype.l1"  "celltype.l2" 
[11] "celltype.l3"  "Phase"        "nCount_SCT"   "nFeature_SCT" "X_index"
```

**Comment by cornhundred** [comment]
Thanks @andrewwbutler!

In a slightly related question, I'm trying to convert this dataset to anndata in order to work in Scanpy in python but I'm running into a conversion issue (https://github.com/mojaveazure/seurat-disk/issues/44#issuecomment-780740508). Is there an easy way to export this cell type metadata, gene expression counts, and ADT counts as CSVs?

**Comment by andrewwbutler** [comment]
The raw data is available [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378) if you want CSVs. To extract from a Seurat object, you can use `GetAssayData` and then `write.csv`. For the metadata, you can pull as above with `ref[[]]` and similarly export to a file with `write.csv`.

**Comment by cornhundred** [comment]
Thanks @andrewwbutler that works :)
