### ISSUE TITLE
  could not find function "LoadReference"

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/azimuth#46]
reference <-LoadReference(path = "https://seurat.nygenome.org/azimuth/references/v1.0.0/human_pbmc")
Error in LoadReference(path = "https://seurat.nygenome.org/azimuth/references/v1.0.0/human_pbmc") :
  could not find function "LoadReference"

I installed Azimuth but it does not have function called LoadRefernce.

**Comment by andrewwbutler** [comment]
Hi,

This function was meant primarily to be used in the context of the Azimuth app so it is not an exported function. However, you can still access it in one of two ways: 

1. `Azimuth:::LoadReference()` 
2.  If you have cloned the repository, you can load all functions (including internal) with `devtools::load_all()`

**Comment by FADHLyemen** [comment]
Thank you, it works.
