### ISSUE TITLE
Warning: Error in -: invalid argument to unary operator

### ISSUE THREAD

**Issue by bloughstephen** [satijalab/azimuth#49]
when we run our reference through a config file, after all of the data processing finished and before we could use the interactive features of the app, we got this error : Warning: Error in -: invalid argument to unary operator. I was curious why this occurred after all of the processing finished?

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Can you try installing the latest version of Azimuth? I believe this bug was fixed recently before the latest release (0.3.0) but if it persists, can you provide a reproducible example for us to try and debug further?

**Comment by bloughstephen** [comment]
Updating to the latest version has fixed this issue. 
Thanks!

**Comment by iichelhadi** [comment]
Hi
This issue occurs with v0.4.6 as well. Any solutions?
Regards
