### ISSUE TITLE
Deploying to the web

### ISSUE THREAD

**Issue by bloughstephen** [satijalab/azimuth#55]
Hi again,

I was wondering how I could deploy an version of the app using my own reference to the web. Is there any particular way that you recommend I do so? I tried to just deploy from the RStudio using the publish button but that didn't work out for me. 

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Our web deployment strategy for the apps that we host is adapted from the setup described in this blog post [here](https://www.databentobox.com/2020/05/31/shinyproxy-with-docker-swarm/).
