### ISSUE TITLE
What happens to data uploaded to Azimuth

### ISSUE THREAD

**Issue by SirKuikka** [satijalab/azimuth#56]
Hi,

I have been going through the Azimuth tool documentation, but I haven't seen information about what happens to the data uploaded to Azimuth after the analysis. Do you save the gene expression count data so that it can be used in improving the service, the method or something like that?

**Comment by andrewwbutler** [comment]
Hi,

The data that is uploaded is never saved in any way. We do collect a few general usage statistics to get a sense of how many cells are being uploaded, which reference was used, how long the mapping took, etc, but we never save any of the expression data or mapping results on our end.
