### ISSUE TITLE
forwarding weblink on http://azimuth.satijalab.org/app/azimuth incorct

### ISSUE THREAD

**Issue by ergonyc** [satijalab/azimuth#60]
The hyperlink where it says azimuth has migrated to is incorrect.  

it's linked as: http://azimuth.satijalab.org/app_direct/azimuth/azimuth.hubmapconsortium.org
should probably be: https://azimuth.hubmapconsortium.org

Apologies if this does not belong here. Just trying to help.

**Comment by jaisonj708** [comment]
Thanks for pointing this out, the link should work now if you clear browser cache.
