### ISSUE TITLE
Error when running docker container

### ISSUE THREAD

**Issue by doncarlos999** [satijalab/azimuth#63]
Hi there,

Thanks for sharing azimuth.

I am trying to run azimuth on an AWS EC2 instance using a docker container built from the dockerfile in the repo. The shiny server runs successfully and I am able to connect via the website but as soon as I click on the azimuth page it goes grey and i see the following error messages in the terminal:
<img width="414" alt="Screenshot 2021-06-04 at 14 33 40" src="https://user-images.githubusercontent.com/29129699/120809345-dc082700-c541-11eb-8917-ce533304a267.png">

I see that this error comes from line 208 in the server.R file and mentions demos. Do I need to include a demo file alongside the reference files or is there a way to disable the demo so that the app doesn't crash?

Thank you in advance.

**Comment by andrewwbutler** [comment]
Hi,

Yes, for now a demo dataset is required. We will look into making this optional so it doesn't crash without one but the easiest solution currently is to just specify a demo file (can just be a trivial/dummy dataset to get it running).

**Comment by doncarlos999** [comment]
Thanks for the super quick response. 
Where in the docker run command should I specify the demo dataset?

**Comment by andrewwbutler** [comment]
You can specify it in the `AzimuthApp` command. E.g.

```
docker run -it -p 3838:3838 -v /path/to/reference:/reference-data:ro azimuth R -e "Azimuth::AzimuthApp(reference = '/reference-data', demodataset = 'demo.rds')"
```

Alternatively, we often use a config file to specify a lot of these kinds of things. You can see examples of those in the [azimuth-references repo](https://github.com/satijalab/azimuth-references) --- e.g. [here](https://github.com/satijalab/azimuth-references/blob/master/human_motorcortex/reference/config.json). In that case the docker command would look more like.

```
docker run -it -p 3838:3838 -v /path/to/reference:/reference-data:ro azimuth R -e "Azimuth::AzimuthApp(config='/reference-data/config.json')"
```

**Comment by doncarlos999** [comment]
This solved the demo dataset problem. Thanks for that. 
But now I get another error about missing homolog file: 
"Homolog file doesn't exist at path provided:". 
I manually downloaded the homolog file from 'https://seurat.nygenome.org/azimuth/references/homologs.rds' and added 
`homolog.table <- /path/to/homologs.rds;` before the Azimuth run command but the error still appears. Is there a way to declare the path to the homolog file?
Thanks again for helping with this.

**Comment by andrewwbutler** [comment]
You should be able to specify it similarly to the demodataset. E.g.

```
docker run -it -p 3838:3838 -v /path/to/reference:/reference-data:ro azimuth R -e "Azimuth::AzimuthApp(reference = '/reference-data', demodataset = 'demo.rds', homologs = 'homologs.rds')"
```

**Comment by doncarlos999** [comment]
Awesome, looks like it is working perfectly now. Thanks a lot for the help!

**Comment by andrewwbutler** [comment]
Closing this thread as providing a `demodataset` should be optional now on the `develop` branch as of (#64).
