### ISSUE TITLE
Human Fetus reference did not work for anchor finding by R script template

### ISSUE THREAD

**Issue by soontide** [satijalab/azimuth#66]
Hello there,

I have tried to work on a public PBMC dataset (https://cellexalvr.med.lu.se/downloadable/pbmc3k.zip) by downloading the reference data from Zenodo (ref.Rds and idx.annoy) and applying the Azimuth's R script template. 

It worked well when using the Human PBMC and the Human Lung references, returning 2754 and 2460 anchors, respectively. But when using the Human Fetus reference, it stuck at the anchor finding step, reporting the following error:

Error in index$getNNsByVectorList(query[x, ], k, search.k, include.distance) : 
  fv.size() != vector_size
  
Here is the code (same for Human PBMC and Human Lung references except the reference path):

library("Seurat")
library("Azimuth")
query <- LoadFileInput(path = "./pbmc3k.h5ad")
reference <- LoadReference(path = "./azimuthRefs/humanFetus/")
query <- ConvertGeneNames(object = query, reference.names = rownames(x = reference$map), homolog.table = "./azimuthRefs/homologs.rds")
query <- SCTransform(object = query, assay = "RNA",  new.assay.name = "refAssay",  residual.features = rownames(x = reference$map), 
 reference.SCT.model = reference$map[["refAssay"]]@SCTModel.list$refmodel,  method = 'glmGamPoi',  ncells = 2000,  n_genes = 2000,  
 do.correct.umi = FALSE,  do.scale = FALSE,  do.center = TRUE)
anchors <- FindTransferAnchors(  reference = reference$map,  query = query,  k.filter = NA,  reference.neighbors = "refdr.annoy.neighbors",
  reference.assay = "refAssay",  query.assay = "refAssay",  reference.reduction = "refDR",  normalization.method = "SCT",
    features = intersect(rownames(x = reference$map), VariableFeatures(object = query)),  dims = 1:50,
  n.trees = 20,  mapping.score.k = 100)

On the other hand, this public PBMC dataset could be safely analyzed by the Azimuth online Web App using the Human Fetus reference. So I am really confused about what is wrong.

Thank you in advance!

**Comment by andrewwbutler** [comment]
Hi,

Sorry for the confusion here. For the human fetus reference specifically, we built the index using 100 dimensions so you need to adjust the `FindTransferAnchors` function call respectively (set `dims = 1:100` rather than `1:50`). The parameter is configurable in the app, which was why it runs online but looks like it didn't get propagated to programmatically fill in the template script as well. We'll work on a fix to update the downloadable script.

**Comment by soontide** [comment]
Thank you for this explanation, the script works well now after change the dims to 1:100.
