### ISSUE TITLE
 Error in run Azimuth::AzimuthApp()

### ISSUE THREAD

**Issue by Totoro-chen** [satijalab/azimuth#68]
I'm try to use Azimuth in R(Rstudio),  Following problems are encountered according to the official tutorial：
>   Azimuth::AzimuthApp()

Listening on http://127.0.0.1:6914
Warning: Error in :: Parameter length is zero
  51: paste0
  50: server
Error in 1:nrow(x = demos) : Parameter length is zero

I didn't find a parameter to specify 50 or 51，How do I deal with this problem?
Looking forward to your answer

**Comment by doncarlos999** [comment]
Hi Totoro-chen

I had the same issue but the solution is [here](https://github.com/satijalab/azimuth/issues/63).

**Comment by Totoro-chen** [comment]
Thanks for the super quick response.
This solved the demo dataset problem. Thanks for that.
But now I get another problem:
I had provided reference data pathway and demo dataset
>Azimuth::AzimuthApp(reference = "E:/project/2021_04_PBMC_5mRNA/analysis/mRNA/Integrate/azimuth_ref/" ,demodataset = 'demo.rds') 

Listening on http://127.0.0.1:7817
Warning: Error in curl::curl_fetch_memory: Could not resolve host: E
  64: curl::curl_fetch_memory
  63: request_fetch.write_memory
  61: request_perform
  60: httr::GET
  56: FUN
  55: vapply
  54: LoadReference
  50: server
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: E
Thanks again for helping with this.
