### ISSUE TITLE
Error in curl::curl_fetch_memory: Could not resolve host: E

### ISSUE THREAD

**Issue by Totoro-chen** [satijalab/azimuth#69]
Thanks for the super quick response.
This solved the demo dataset problem. Thanks for that.
But now I get another problem:
I had provided reference data pathway and demo dataset
>Azimuth::AzimuthApp(reference = "E:/project/2021_04_PBMC_5mRNA/analysis/mRNA/Integrate/azimuth_ref/" ,demodataset = 'demo.rds') 

Listening on http://127.0.0.1:7817
Warning: Error in curl::curl_fetch_memory: Could not resolve host: E
  64: curl::curl_fetch_memory
  63: request_fetch.write_memory
  61: request_perform
  60: httr::GET
  56: FUN
  55: vapply
  54: LoadReference
  50: server
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: E
Is there any problem with my network? Thanks again for helping with this.

_Originally posted by @Totoro-chen in https://github.com/satijalab/azimuth/issues/68#issuecomment-867531759_

**Comment by andrewwbutler** [comment]
Hi,

It looks like this was a bug in how Windows-style paths were being handled. I've pushed a fix to the `fix/WindowsPath` branch. Please try installing there and see if that resolves the issue.

```R
remotes::install_github("satijalab/seurat", ref = "fix/WindowsPath")
```

**Comment by KMulder-IGR** [comment]
Hello,

I also ran into the same error as described, but when trying to install the suggested fix, I ran into the error that the fixed Seurat version does not exist. 

> remotes::install_github("satijalab/seurat", ref = "fix/WindowsPath")
Downloading GitHub repo satijalab/seurat@fix/WindowsPath
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/satijalab/seurat/tarball/fix%2FWindowsPath'

**Comment by andrewwbutler** [comment]
Ahh sorry, should be installing Azimuth (not Seurat) as that's where the problem/fix is. 

```R
remotes::install_github("satijalab/azimuth", ref = "fix/WindowsPath")
```
