### ISSUE TITLE
General question regarding how different batches samples are dealt with in Azimuth

### ISSUE THREAD

**Issue by HaniJieunKim** [satijalab/azimuth#70]
Dear Developers,

Thank you for creating an amazing tool Azimuth! 

I just had a naive question regarding how Azimuth deals with a scRNA-seq data that may come from different batches and samples. Is the user expected to upload the count matrix that has been subsetted to contains cells from individual batches/samples? 

Thank you for your time. 

Best regards,

Hani

**Comment by andrewwbutler** [comment]
Hi Hani,

Please see the FAQ [here](https://azimuth.hubmapconsortium.org/#Should%20I%20map%20my%20batches%20separately%20or%20combined%3f).

**Comment by HaniJieunKim** [comment]
Thanks Andrew! It's great to know Azimuth works well on different batches combined. Would there be some reference I could refer to? There is not much detail in the link other than that the outputs are very similar when mapping batches separately or combined and that Azimuth can successfully remove batch effect. It would be great to know how it is able to do this. Thanks again.

**Comment by andrewwbutler** [comment]
There is some description of the procedure in the [v4 paper](https://www.cell.com/cell/fulltext/S0092-8674%2821%2900583-3) (see the section "Reference-based Integration for query datasets"). Essentially, we are using the anchor-based integration methodology to remove batch effects and place the new data in the same space as the reference. The main difference here is that we perform this "correction" in the projected low dimensional space as opposed to gene expression space.

**Comment by HaniJieunKim** [comment]
Great! Thank you very much
