### ISSUE TITLE
Is there a limit to how many times I can use AZIMUTH WEB?

### ISSUE THREAD

**Issue by levinhein** [satijalab/azimuth#76]
Hello. I used Azimuth continously now for like 8 PBMC datasets, they all went smoothly. On my next run, the AZIMUTH PBMC web app turned white every time I visit it. Whether, I refresh or close it and visit it again.

But this only happens in PBMC app. Other apps like Pancreas, Lung, Kidney etc all function normally.

**Comment by andrewwbutler** [comment]
Hi,

While there are limits on the size of individual datasets that you can upload, there shouldn't be any limits on the number of datasets. Is this problem still persisting and if so can you provide the debug ID found in the bottom left of the sidebar?
