### ISSUE TITLE
Label my own UMAP with Azimuth?

### ISSUE THREAD

**Issue by algarji** [satijalab/azimuth#78]
I was wondering if Azimuth can automatically label my own UMAP instead of the reference UMAP provided, as for example SignacX package do. Thank you.

**Comment by andrewwbutler** [comment]
Hi,

Azimuth doesn't support uploading a user-specified UMAP. However, it will return predicted cell types for your data that you can download after running. These could then be loaded into a Seurat object with any UMAP and displayed on that plot.

**Comment by algarji** [comment]
Excuse me, but I encountered another issue regarding Azimuth @andrewwbutler . It seems that it supports a max input size of 1gb. Since RDS files are usually heavy (I have for example 6,5k cells and more than 1 gb of RDS exporting from seurat), is there a solution or is this gonna change? thank you.

**Comment by andrewwbutler** [comment]
You only need to upload the counts matrix, which for 6.5k cells shouldn't be close to 1gb. One other thing you could try is slimming down the Seurat object before uploading. E.g.

```R
DefaultAssay(object) <- “RNA”
object <- DietSeurat(object = object, assays = “RNA”)
```
