### ISSUE TITLE
Cannot add ADT to seurat object

### ISSUE THREAD

**Issue by m0nib** [satijalab/azimuth#80]
Hi,

when loading a demo dataset i keep getting the following error:

Listening on http://127.0.0.1:4276
[1] "resetting..."
detected inputs from HUMAN with id type Gene.name
reference rownames detected HUMAN with id type Gene.name
Warning: Removed 1 rows containing missing values (geom_hline).
Warning: Removed 1 rows containing missing values (geom_rect).
Warning: Removed 1 rows containing missing values (geom_hline).
Warning: Removed 1 rows containing missing values (geom_rect).
Warning: Transformation introduced infinite values in continuous y-axis
Warning: Transformation introduced infinite values in continuous y-axis
Warning: Transformation introduced infinite values in continuous y-axis
Warning: Transformation introduced infinite values in continuous y-axis
Warning: Transformation introduced infinite values in continuous y-axis
Warning: Removed 1 rows containing missing values (geom_hline).
Warning: Removed 1 rows containing missing values (geom_rect).
Warning: Removed 1 rows containing missing values (geom_hline).
Warning: Removed 1 rows containing missing values (geom_rect).
Using reference SCTModel to calculate pearson residuals
Determine variable features
Calculating residuals of type pearson for 2301 genes
  |===================================================================================================================================================================| 100%
  |===================================================================================================================================================================| 100%
Set default assay to refAssay
Normalizing query using reference SCT model
Projecting cell embeddings
Finding query neighbors
Finding neighborhoods
Finding anchors
	Found 7346 anchors
Warning: Error in : Cannot find 'ADT' in this Seurat object
  4: runApp
  1: Azimuth::AzimuthApp

> traceback()
14: execCallbacks(timeoutSecs, all, loop$id)
13: run_now(timeoutMs/1000, all = FALSE)
12: service(timeout)
11: serviceApp()
10: ..stacktracefloor..(serviceApp())
9: withCallingHandlers(expr, error = doCaptureStack)
8: domain$wrapSync(expr)
7: promises::with_promise_domain(createStackTracePromiseDomain(), 
       expr)
6: captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
       }
   })
5: ..stacktraceoff..(captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
       }
   }))
4: runApp(appDir = shinyApp(ui = AzimuthUI, server = AzimuthServer))
3: force(code)
2: with_options(new = opts, code = runApp(appDir = shinyApp(ui = AzimuthUI, 
       server = AzimuthServer)))
1: Azimuth::AzimuthApp(config = "./data/config.json")

Not sure what is happening here.

Best regards
Monib

**Comment by andrewwbutler** [comment]
Hi,

If you are mapping against a reference that does not contain ADTs, you need to set the `Azimuth.app.do_adt` option to `FALSE`. For an example config file that does this, please see the lung one [here](https://github.com/satijalab/azimuth-references/blob/master/human_lung/reference/config.json).
