### ISSUE TITLE
Big Input file error reading from connection

### ISSUE THREAD

**Issue by juechenyang** [satijalab/azimuth#85]
Hi，

I am using local version of Azimuth and trying to input a big seurat data rds(size=5G) for analysis. I have adjusted the config file by setting `shiny.maxRequestSize = 1048576000` which is **10 times of default**. However, I always see message from web interface like:
![image](https://user-images.githubusercontent.com/18729321/140254410-cacbe518-22e7-401c-9fd6-1379649a1d9f.png)

Is there any way to avoid this issue? Or it is not recommended to do large files with Azimuth

Thank you!

**Comment by andrewwbutler** [comment]
Hi,

Is this problem unique to large files or does any file fail to load? One other thing to check here is that the directory from which you are trying to load the query file bind mounted appropriately.

**Comment by juechenyang** [comment]
Hi,

Big files(usually > 4G) always stuck at "error reading from connection". However, small files sometimes stuck at there but can be solved by refreshing the webpage and reload the data. I think there is no issue for uploading the data because I can always see "resetting..." at the backend terminal even the message of "error reading from connection" comes out later.

Thank you

**Comment by andrewwbutler** [comment]
What is the message in the terminal when you see the "error reading from connection" message in the GUI? Can you also post the full command you ran to start the docker container?

**Comment by juechenyang** [comment]
Hi,

When I see "error reading from connection" message in the GUI, there was no error message that comes out from terminal but stuck at "resetting...". Here is my full command of running docker:

`docker run -it --name JasonAzimuth -p 3838:3838 -v /Volumes/Jason/docker_dir/references:/reference-data:ro satijalab/azimuth:0.4.3 R -e "Azimuth::AzimuthApp(reference = '/reference-data', config = '/reference-data/config.json')"`

Thank you!

**Comment by andrewwbutler** [comment]
Hmm, I am not able to reproduce this error unless I give it a path to a file that doesn't exist.  Are you able to load the problematic files separately outside of Azimuth/docker? Not really a solution to the underlying issue but you could try shrinking the object with `DietSeurat` first if it contains a lot of extraneous information (e.g. `scale.data`, other `Assay`s, etc).

**Comment by juechenyang** [comment]
Thank you and yes, DietSeurat works for me at this point. But just let you know that this "error reading from connection" also happens occasionally on small files(<1G) although it can be solved by either refresh page or upload again.

Thank you!
