### ISSUE TITLE
Conflicting Level1 and Level2 labels

### ISSUE THREAD

**Issue by sinanassiri** [satijalab/azimuth#86]
Dear Azimuth team,

Thanks for this great resource.

I have been exploring the PBMC reference to annotate some internal query samples. Closer inspection of level1 and level2 labels in the query data revealed some conflicting labels, for example a cell is called "CD4 T" at level1, but "CD14 Mono" or "CD8 TCM" at level 2. While these cases are typically rare (less than 1%), I was wondering if you have encountered conflicting Level1 and Level2 labels, and what your thoughts are on the possible explanation(s).

Many thanks,
Sina

**Comment by andrewwbutler** [comment]
Hi Sina,

Azimuth isn't imposing any strict hierarchy on `level1` vs `level2` here so it's theoretically possible that in rare cases you could get conflicting labels. I would imagine that in those cases you probably have fairly similar prediction scores at the first level (i.e. in your example, similar prediction scores for CD4T and CD8T). I would take look at these prediction scores at both levels and see if the cells with conflicting labels have poor prediction scores to begin with.

**Comment by sinanassiri** [comment]
Thanks for the comment, Andrew. I tried looking up the definition of "**prediction score**" so that I can interpret poor scores, but could not find any mention of prediction score in the azimuth paper (Hao et al 2021) or Seurat documentations. Can you please elaborate (or point me to a reference) on how exactly the prediction scores are computed?

I found the following descriptive statements on https://azimuth.hubmapconsortium.org/, which I include here for completeness:

- Cell prediction scores range from 0 to 1 and reflect the confidence associated with each annotation. Cells with high-confidence annotations (for example, prediction scores > 0.75) reflect predictions that are supported by multiple consistent anchors.
- A cell can get a low prediction score because its probability is equally split between two clusters (for example, for some cells, it may not be possible to confidently classify them between the two possibilities of CD4 Central Memory (CM), and Effector Memory (EM), which lowers the prediction score, but the mapping score will remain high.
- A high prediction score means that a high proportion of reference cells near a query cell have the same label. However, these reference cells may not represent the query cell well, resulting in a low mapping score.

Thank you,
Sina

**Comment by andrewwbutler** [comment]
You can see the full definition for this in the [Cell 2019](https://www.sciencedirect.com/science/article/pii/S0092867419305598?via%3Dihub) paper. Specifically, the "Label Transfer" sections. This is also described in the documentation for the `TransferData` function [here](https://satijalab.org/seurat/reference/transferdata).
