### ISSUE TITLE
Does Azimuth App requires internet connect?

### ISSUE THREAD

**Issue by Zepeng-Mu** [satijalab/azimuth#87]
Hello, I'm getting an error:
```
Timeout was reached: [seurat.nygenome.org] Connection timeout after 10001 ms
```
when running Azimuth App from my own installation. Does this mean Azimuth requires internet even when using my local ref files? Is there a way that I can run this without internet on computational clusters.

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

No, if you are running the app yourself it doesn't require an internet connection. In addition to the reference files, make sure you also have a local copy of the `homologs.rds` file (which can be downloaded [here](https://seurat.nygenome.org/azimuth/references/homologs.rds)) and specify this in your config or run command.

**Comment by Zepeng-Mu** [comment]
It works now. Thanks!

**Comment by bontix-77** [comment]
> Hi,
> 
> No, if you are running the app yourself it doesn't require an internet connection. In addition to the reference files, make sure you also have a local copy of the `homologs.rds` file (which can be downloaded [here](https://seurat.nygenome.org/azimuth/references/homologs.rds)) and specify this in your config or run command.

may you please not be generic and list exactly all the files required and how to use them. i'd appreciate.
