### ISSUE TITLE
FindTransferAnchors error in R script

### ISSUE THREAD

**Issue by yannk-lm** [satijalab/azimuth#89]
Hello,
Thank you for this great app.
I'm using Azimuth 0.4.3 and Seurat 4.0.4.

I ran Azimuth online using the PBMC reference with my dataset of ~6k NK/T cells. 
Even though I got 12.74% of query cells with anchors and a 2.63/5, cluster preservation score, which I assume is due to the use of a homogeneous group of cells, I had coherent results.

After downloading the analysis script template, I tried to replicate the online analysis but at the FindTransferAnchors step I get this issue :
Error in idx[i, ] <- res[[i]][[1]] : 
  argument is of length zero

I used the default arguments in the script, which were the following :

FindTransferAnchors(
  reference = reference$map,
  query = query,
  k.filter = NA,
  reference.neighbors = "refdr.annoy.neighbors",
  reference.assay = "refAssay",
  query.assay = "refAssay",
  reference.reduction = "refDR",
  normalization.method = "SCT",
  features = intersect(rownames(x = reference$map), VariableFeatures(object = query)),
  dims = 1:50,
  n.trees = 20,
  mapping.score.k = 100)

Any idea on what is causing this issue ?

Regards,
Yannick

**Comment by AbigailRG-dev** [comment]
I managed to at least get a result by using reference.neighbors = NULL instead of refdr.annoy.neighbors.
I know too little of the functions at the moment to tell you more, though.
