### ISSUE TITLE
Deploying strategy

### ISSUE THREAD

**Issue by juechenyang** [satijalab/azimuth#90]
Hi,

I am a Phd student learning how to deploy shiny app. I wonder if you would mind to describe how did you deploy this azimuth app at:
https://azimuth.hubmapconsortium.org/
In the meantime, how did you handle **concurrent users** for this online azimuth shiny app.

Thank you!

**Comment by andrewwbutler** [comment]
The deployment is similar to the approach described in [this](https://www.databentobox.com/2020/05/31/shinyproxy-with-docker-swarm/) blog post. Multiple users are handled with docker swarm and shinyproxy.
