### ISSUE TITLE
Batch effect correction

### ISSUE THREAD

**Issue by sgheo** [satijalab/azimuth#91]
Thank you for creating Azimuth.
It is amazing!

According to the guide, the input single cell RNA seq data must be unnnormalized.
I wonder that if a batch effect correction step can be processed before or during the Azimuth process?

Luke Heo

**Comment by andrewwbutler** [comment]
Hi Luke,

Yes the input data should not be normalized (just the raw count data). Azimuth does remove batch effects between the reference and query as part of the mapping pipeline.  If you are asking whether to map multiple batches separately or together, this is addressed in the FAQ [here](https://azimuth.hubmapconsortium.org/#Should%20I%20map%20my%20batches%20separately%20or%20combined%3f).

**Comment by sgheo** [comment]
Thank you so much ^^
It is clear by now.
