### ISSUE TITLE
A Seurat object for Azimuth PBMC reference? 

### ISSUE THREAD

**Issue by apredeus** [satijalab/azimuth#98]
Hi, 

We're testing a new clustering algorithm, and would love to have the Azimuth reference to work with, since it's so wonderfully annotated. However, the link provided https://zenodo.org/record/4546839 - has the object that's stripped of all gene expression data from what I can tell. Is it possible to get the Seurat object for the reference 36k cells with RNA assay and all? Otherwise, would be grateful if you can point me to notebooks/code used to integrate all the raw data that went into the Azimuth PBMC reference. 

Thank you in advance!

**Comment by andrewwbutler** [comment]
Hi,

The reference on Zenodo is provided as minimally as possible (i.e. only what is needed for mapping with Azimuth). The full expression data is available on GEO [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378). If you want to exactly reproduce what's in the Azimuth reference, the code for that is [here](https://github.com/satijalab/azimuth-references/tree/master/human_pbmc). You probably want to run the `export_zarr` rule and then the resulting `vitessce_ref.h5Seurat` is likely what you're looking for.

**Comment by apredeus** [comment]
Great, thank you very much! This should be all we need to proceed.

**Comment by ggruenhagen3** [comment]
The lightweight objects w/o gene expression is convenient for quick mapping w/ Azimuth. But it would also be convenient for the full objects to easily available.
