### ISSUE TITLE
Human Bone Marrow Reference

### ISSUE THREAD

**Issue by MjelleLab** [satijalab/azimuth#99]
Hi,
I wonder what the link is for the Human Bone Marrow Reference?

**Comment by AustinHartman** [comment]
Hi - you can find the app, vitessce reference explorer, and links to download the reference here: [https://azimuth.hubmapconsortium.org/references/#Human%20-%20Bone%20Marrow](https://azimuth.hubmapconsortium.org/references/#Human%20-%20Bone%20Marrow)

**Comment by MjelleLab** [comment]
In the app, there link in the R script is not correct. For the PBMC
datasets it links to a specific file, but not for bone marrow.

man. 28. mar. 2022, 22:14 skrev Austin Hartman ***@***.***>:

**Comment by AustinHartman** [comment]
Could you provide more details? I'm not sure which link and which R script you're referring to.

**Comment by MjelleLab** [comment]
I file similar to this:

reference <- LoadReference(path = "
https://seurat.nygenome.org/azimuth/references/v1.0.0/human_pbmc")
----

Robin Mjelle
PhD
Department of Cancer Research and Molecular Medicine
Faculty of Medicine
Laboratory Centre, 5th floor. Erling Skjalgssons gt. 1
Norwegian University of Science and Technology NTNU
7030 Trondheim, Norway
Cell. phone: +47 40234780

**Comment by AustinHartman** [comment]
you can use `bonemarrow.reference <- LoadReference(path = "https://seurat.nygenome.org/azimuth/references/v1.0.0/human_bonemarrow")` if you wish to access the bone marrow reference by web URL
